import { useEffect, useMemo, useRef, useState } from 'react';
import { DndProvider, useDrag, useDrop } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';
import { ArrowRight, GripVertical, ListOrdered, Save, Trash2, X } from 'lucide-react';
import { useAdmin } from '../context/AdminContext';
import { useProjects } from '../context/ProjectContext';
import { EnrichedTask, useTasks } from '../context/TaskContext';
import { FilterCondition, OperationalPriorityEntry, PriorityCycle, PriorityCycleType, Project, SavedView } from '../types';
import { canManageOperationalPriority, canManageWeeklyFocus } from '../utils/permissions';
import { SearchableSelect } from '../components/filters/SearchableSelect';
import { DynamicFiltersPanel } from '../components/filters/DynamicFiltersPanel';
import { UnifiedFilterPanel } from '../components/filters/UnifiedFilterPanel';
import { getUserTeams } from '../utils/userTeams';
import { applyDynamicFilters, DynamicFilterFieldDefinition } from '../utils/dynamicFilters';
import { useSavedViews } from '../hooks/useSavedViews';
import { AppErrorBoundary } from '../components/shared/AppErrorBoundary';
import {
  getPriorityCycleBehaviorLabel,
  getPriorityCycleTypeBadgeClasses,
  getPriorityCycleTypeLabel,
} from '../utils/priorityCyclePresentation';
import {
  KanbanDropPlacement,
  moveItemBetweenLists,
  moveItemWithinList,
} from '../utils/kanbanReorderUtils';
import {
  calculatePriorityCycleEndDate,
  getPriorityCycleDefaultDuration,
  getPriorityCycleDurationDays,
  getPriorityCycleSuggestedName,
  isPriorityCycleAutoScheduled,
  isPriorityCycleStructureLocked,
} from '../utils/priorityCycles';

type PriorityCandidateType = 'task' | 'project';
type PriorityScope = 'projects' | 'tasks';

const PRIORITY_SCOPE_STORAGE_KEY = 'crisdu_operational_priority_scope';

interface PriorityCandidate {
  id: string;
  entityId: string;
  itemType: PriorityCandidateType;
  title: string;
  assigneeId: string;
  assigneeName: string;
  workspace: string;
  projectId?: string;
  projectName?: string;
  operationalStatus: 'active' | 'paused' | 'completed' | 'cancelled';
  statusLabel: string;
  badge: string;
  secondary: string;
}

interface PriorityDragItem {
  candidateId: string;
  sourceList: 'prioritized' | 'backlog';
}

interface PriorityCycleDraft {
  editingId: string | null;
  name: string;
  description: string;
  type: PriorityCycleType;
  startDate: string;
  endDate: string;
  durationDays: string;
  active: boolean;
  nameAutoGenerated: boolean;
}

function buildCandidateId(itemType: PriorityCandidateType, entityId: string) {
  return `${itemType}:${entityId}`;
}

function createInitialCycleDraft(): PriorityCycleDraft {
  const now = new Date();
  const startDate = now.toISOString().slice(0, 10);
  const durationDays = String(getPriorityCycleDefaultDuration('week') || 7);
  const endDate = calculatePriorityCycleEndDate(startDate, Number(durationDays));

  return {
    editingId: null,
    name: getPriorityCycleSuggestedName({ type: 'week', startDate }),
    description: '',
    type: 'week',
    startDate,
    endDate,
    durationDays,
    active: true,
    nameAutoGenerated: true,
  };
}

interface OperationalPriorityContentProps {
  embedded?: boolean;
  workspaceFilter?: string[];
  defaultScope?: PriorityScope;
}

const OPERATIONAL_STATUS_LABELS = {
  active: 'Ativo',
  paused: 'Pausado',
  completed: 'Concluído',
  cancelled: 'Cancelado',
} as const;

function PriorityCard({
  candidate,
  sourceList,
  isFocused,
  canManageQueue,
  canManageFocus,
  onMove,
  onRemove,
  onToggleFocus,
}: {
  candidate: PriorityCandidate;
  sourceList: 'prioritized' | 'backlog';
  isFocused: boolean;
  canManageQueue: boolean;
  canManageFocus: boolean;
  onMove: (
    candidateId: string,
    sourceList: 'prioritized' | 'backlog',
    targetList: 'prioritized' | 'backlog',
    targetCandidateId?: string,
    placement?: KanbanDropPlacement
  ) => void;
  onRemove?: () => void;
  onToggleFocus?: () => void;
}) {
  const cardRef = useRef<HTMLDivElement | null>(null);
  const [{ isDragging }, drag] = useDrag(
    () => ({
      type: 'OP_PRIORITY_ITEM',
      item: { candidateId: candidate.id, sourceList } as PriorityDragItem,
      canDrag: canManageQueue,
      collect: (monitor) => ({
        isDragging: monitor.isDragging(),
      }),
    }),
    [candidate.id, canManageQueue, sourceList]
  );
  const [, drop] = useDrop(
    () => ({
      accept: 'OP_PRIORITY_ITEM',
      drop: (item: PriorityDragItem, monitor) => {
        if (item.candidateId === candidate.id) return;
        const clientOffset = monitor.getClientOffset();
        const bounds = cardRef.current?.getBoundingClientRect();
        const placement: KanbanDropPlacement =
          clientOffset && bounds && clientOffset.y < bounds.top + bounds.height / 2
            ? 'before'
            : 'after';
        onMove(item.candidateId, item.sourceList, sourceList, candidate.id, placement);
        return { handled: true };
      },
    }),
    [candidate.id, onMove, sourceList]
  );

  return (
    <div
      ref={(node) => {
        cardRef.current = node;
        drag(node);
        drop(node);
      }}
      className={`rounded-xl border px-4 py-3 transition-all ${
        isFocused ? 'border-amber-300 bg-amber-50' : 'border-gray-200 bg-white'
      } ${isDragging ? 'opacity-50' : ''}`}
    >
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0 flex-1">
          <div className="mb-2 flex flex-wrap items-center gap-2">
            <span className="inline-flex rounded-full bg-slate-100 px-2 py-0.5 text-[11px] font-medium text-slate-700">
              {candidate.badge}
            </span>
            <span className="inline-flex rounded-full bg-gray-100 px-2 py-0.5 text-[11px] text-gray-600">
              {candidate.statusLabel}
            </span>
            {isFocused && (
              <span className="inline-flex rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-medium text-amber-800">
                Foco
              </span>
            )}
          </div>
          <p className="truncate text-sm font-semibold text-gray-900">{candidate.title}</p>
          <p className="mt-1 text-xs text-gray-500">{candidate.secondary}</p>
          {candidate.projectName && (
            <p className="mt-1 text-xs text-gray-500">Projeto: {candidate.projectName}</p>
          )}
        </div>

        <div className="flex items-center gap-2">
          {canManageQueue ? <GripVertical className="h-4 w-4 text-gray-400" /> : null}
          {canManageFocus ? (
            <button
              onClick={onToggleFocus}
              className={`rounded-lg border px-3 py-2 text-xs font-medium transition-colors ${
                isFocused
                  ? 'border-amber-300 bg-amber-100 text-amber-900 hover:bg-amber-200'
                  : 'border-slate-200 bg-white text-slate-700 hover:bg-slate-50'
              }`}
              title={isFocused ? 'Remover foco da semana' : 'Marcar foco da semana'}
            >
              {isFocused ? 'Remover foco' : 'Foco da semana'}
            </button>
          ) : null}
          {canManageQueue && sourceList === 'backlog' ? (
            <button
              onClick={() => onMove(candidate.id, 'backlog', 'prioritized')}
              className="rounded-lg border border-gray-300 p-2 text-gray-600 hover:bg-gray-50"
              title="Priorizar item"
            >
              <ArrowRight className="h-4 w-4" />
            </button>
          ) : null}
          {canManageQueue && sourceList === 'prioritized' ? (
            <button
              onClick={onRemove}
              className="rounded-lg border border-red-200 p-2 text-red-600 hover:bg-red-50"
              title="Remover da fila"
            >
              <Trash2 className="h-4 w-4" />
            </button>
          ) : null}
        </div>
      </div>
    </div>
  );
}

function PriorityList({
  title,
  subtitle,
  candidates,
  listType,
  focusedEntryIds,
  canManageQueue,
  canManageFocus,
  onMove,
  onRemove,
  onToggleFocus,
}: {
  title: string;
  subtitle: string;
  candidates: PriorityCandidate[];
  listType: 'prioritized' | 'backlog';
  focusedEntryIds: Set<string>;
  canManageQueue: boolean;
  canManageFocus: boolean;
  onMove: (
    candidateId: string,
    sourceList: 'prioritized' | 'backlog',
    targetList: 'prioritized' | 'backlog',
    targetCandidateId?: string,
    placement?: KanbanDropPlacement
  ) => void;
  onRemove: (candidateId: string) => void;
  onToggleFocus: (candidate: PriorityCandidate) => void;
}) {
  const [{ isOver }, drop] = useDrop(
    () => ({
      accept: 'OP_PRIORITY_ITEM',
      drop: (item: PriorityDragItem, monitor) => {
        if (monitor.didDrop()) return;
        onMove(item.candidateId, item.sourceList, listType);
      },
      collect: (monitor) => ({
        isOver: monitor.isOver(),
      }),
    }),
    [listType, onMove]
  );

  return (
    <section className="rounded-2xl border border-gray-200 bg-white">
      <div className="border-b border-gray-200 px-5 py-4">
        <div className="flex items-center justify-between gap-3">
          <div>
            <h2 className="text-lg font-semibold text-gray-900">{title}</h2>
            <p className="mt-1 text-sm text-gray-600">{subtitle}</p>
          </div>
          <span className="rounded-full bg-gray-100 px-3 py-1 text-sm font-medium text-gray-700">
            {candidates.length}
          </span>
        </div>
      </div>

      <div
        ref={drop}
        className={`min-h-[420px] space-y-3 p-4 transition-colors ${
          isOver ? 'bg-blue-50' : ''
        }`}
      >
        {candidates.length > 0 ? (
          candidates.map((candidate) => (
            <PriorityCard
              key={candidate.id}
              candidate={candidate}
              sourceList={listType}
              isFocused={focusedEntryIds.has(candidate.id)}
              canManageQueue={canManageQueue}
              canManageFocus={canManageFocus}
              onMove={onMove}
              onRemove={() => onRemove(candidate.id)}
              onToggleFocus={() => onToggleFocus(candidate)}
            />
          ))
        ) : (
          <div className="rounded-xl border border-dashed border-gray-300 bg-gray-50 px-4 py-10 text-center text-sm text-gray-500">
            {listType === 'prioritized'
              ? 'Arraste itens para montar a fila oficial do colaborador.'
              : 'Todos os itens disponíveis já estão priorizados para este colaborador.'}
          </div>
        )}
      </div>
    </section>
  );
}

export function OperationalPriorityContent({
  embedded = false,
  workspaceFilter,
  defaultScope,
}: OperationalPriorityContentProps = {}) {
  const {
    currentUser,
    users,
    teams,
    operationalPriorityEntries,
    priorityCycles,
    addOperationalPriorityEntry,
    addPriorityCycle,
    updatePriorityCycle,
    deletePriorityCycle,
    setPriorityCycleActive,
    deleteOperationalPriorityEntry,
    reorderOperationalPriorityEntries,
  } = useAdmin();
  const { allTasks } = useTasks();
  const { projects } = useProjects();
  const canManageQueue = canManageOperationalPriority(currentUser);
  const canManageFocus = canManageWeeklyFocus(currentUser);
  const canAccessPage = canManageQueue || canManageFocus;
  const showFocusManagement = !embedded && canManageFocus;
  const eligibleUsers = useMemo(
    () => users.filter((user) => user.status === 'active' && user.role !== 'pmo'),
    [users]
  );
  const [selectedAssigneeId, setSelectedAssigneeId] = useState<string>(eligibleUsers[0]?.id || '');
  const [priorityScope, setPriorityScope] = useState<PriorityScope>(() => {
    try {
      if (defaultScope) return defaultScope;
      const stored = localStorage.getItem(PRIORITY_SCOPE_STORAGE_KEY);
      return stored === 'projects' ? 'projects' : 'tasks';
    } catch {
      return defaultScope || 'tasks';
    }
  });
  const [flowFilter, setFlowFilter] = useState('all');
  const [projectFilter, setProjectFilter] = useState('all');
  const [statusFilter, setStatusFilter] = useState('all');
  const [showFilters, setShowFilters] = useState(false);
  const [dynamicConditions, setDynamicConditions] = useState<FilterCondition[]>([]);
  const [activeSavedViewId, setActiveSavedViewId] = useState<string | null>(null);
  const [cycleDraft, setCycleDraft] = useState<PriorityCycleDraft>(() => createInitialCycleDraft());
  const { views, pinnedView, saveView, deleteView, pinView, clearPinnedView } = useSavedViews('governance_priorities');
  const getCycleSuggestedName = (
    type: PriorityCycleType,
    startDate: string,
    editingId?: string | null
  ) =>
    getPriorityCycleSuggestedName({
      type,
      startDate,
      cycles: priorityCycles,
      excludeCycleId: editingId || undefined,
    });
  const getDraftDurationValue = (type: PriorityCycleType, rawValue?: string) => {
    if (type === 'custom') return rawValue || '';
    const fallback = getPriorityCycleDefaultDuration(type) || 1;
    const parsed = Number(rawValue);
    return String(Number.isFinite(parsed) && parsed > 0 ? Math.round(parsed) : fallback);
  };

  useEffect(() => {
    if (embedded) return;
    localStorage.setItem(PRIORITY_SCOPE_STORAGE_KEY, priorityScope);
  }, [embedded, priorityScope]);

  useEffect(() => {
    if (!defaultScope) return;
    setPriorityScope(defaultScope);
  }, [defaultScope]);

  useEffect(() => {
    if (!pinnedView) {
      setDynamicConditions([]);
      setActiveSavedViewId(null);
      return;
    }
    setDynamicConditions(pinnedView.filtersJson || []);
    if (pinnedView.viewMode === 'projects' || pinnedView.viewMode === 'tasks') {
      setPriorityScope(pinnedView.viewMode as PriorityScope);
    }
    setActiveSavedViewId(pinnedView.id);
  }, [pinnedView?.id]);

  const getOperationalStatusForProject = (project: Project) => {
    if (project.situation === 'cancelado' || project.governance?.situation === 'cancelado') {
      return 'cancelled' as const;
    }
    if (project.situation === 'pausado' || project.governance?.situation === 'pausado') {
      return 'paused' as const;
    }
    if ((project.metrics?.progress || 0) >= 100) {
      return 'completed' as const;
    }
    return 'active' as const;
  };

  const getOperationalStatusForTask = (task: EnrichedTask) => {
    const relatedProject = task.projectId
      ? projects.find((project) => project.id === task.projectId)
      : undefined;

    if (relatedProject) {
      const projectStatus = getOperationalStatusForProject(relatedProject);
      if (projectStatus === 'paused' || projectStatus === 'cancelled') {
        return projectStatus;
      }
    }

    if (task.status === 'done') {
      return 'completed' as const;
    }

    return 'active' as const;
  };

  const candidates = useMemo(() => {
    if (!selectedAssigneeId) return [];
    const selectedUser = users.find((user) => user.id === selectedAssigneeId);
    if (!selectedUser) return [];

    const allowedWorkspaces = workspaceFilter?.length
      ? new Set(workspaceFilter)
      : null;

    const taskCandidates: PriorityCandidate[] = allTasks
      .filter((task) => task.assigneeId === selectedAssigneeId || task.assignee === selectedUser.name)
      .map((task: EnrichedTask) => ({
        operationalStatus: getOperationalStatusForTask(task),
        id: buildCandidateId('task', task.id),
        entityId: task.id,
        itemType: 'task',
        title: task.title,
        assigneeId: selectedAssigneeId,
        assigneeName: selectedUser.name,
        workspace: task.flowLabel || (task.projectName ? projects.find((project) => project.id === task.projectId)?.group || 'Operacional' : 'Operacional'),
        projectId: task.projectId,
        projectName: task.projectName,
        statusLabel: OPERATIONAL_STATUS_LABELS[getOperationalStatusForTask(task)],
        badge: task.itemTypeLabel || 'Tarefa',
        secondary: task.hierarchyBreadcrumb || 'Item operacional',
      }))
      .filter((candidate) => !allowedWorkspaces || allowedWorkspaces.has(candidate.workspace));

    const projectCandidates: PriorityCandidate[] = projects
      .filter(
        (project) =>
          project.responsible === selectedUser.name ||
          taskCandidates.some((candidate) => candidate.projectId === project.id)
      )
      .map((project: Project) => ({
        operationalStatus: getOperationalStatusForProject(project),
        id: buildCandidateId('project', project.id),
        entityId: project.id,
        itemType: 'project',
        title: project.name,
        assigneeId: selectedAssigneeId,
        assigneeName: selectedUser.name,
        workspace: project.group || 'Sem workspace',
        projectId: project.id,
        projectName: project.name,
        statusLabel: OPERATIONAL_STATUS_LABELS[getOperationalStatusForProject(project)],
        badge: 'Projeto',
        secondary: `Responsável: ${project.responsible || 'Não informado'}`,
      }))
      .filter((candidate) => !allowedWorkspaces || allowedWorkspaces.has(candidate.workspace));

    return priorityScope === 'projects' ? projectCandidates : taskCandidates;
  }, [allTasks, priorityScope, projects, selectedAssigneeId, users, workspaceFilter]);
  const dynamicFields = useMemo<DynamicFilterFieldDefinition<PriorityCandidate>[]>(
    () => [
      { key: 'title', label: 'Título', valueType: 'text', getValue: (candidate) => candidate.title },
      { key: 'itemType', label: 'Tipo de item', valueType: 'select', getValue: (candidate) => candidate.itemType, options: [{ value: 'project', label: 'Projeto' }, { value: 'task', label: 'Tarefa' }] },
      { key: 'workspace', label: 'Fluxo', valueType: 'select', getValue: (candidate) => candidate.workspace, options: Array.from(new Set(candidates.map((candidate) => candidate.workspace))).map((item) => ({ value: item, label: item })) },
      { key: 'projectName', label: 'Projeto', valueType: 'select', getValue: (candidate) => candidate.projectName, options: Array.from(new Set(candidates.map((candidate) => candidate.projectName).filter(Boolean))).map((item) => ({ value: item as string, label: item as string })) },
      { key: 'assigneeName', label: 'Responsável', valueType: 'select', getValue: (candidate) => candidate.assigneeName, options: eligibleUsers.map((user) => ({ value: user.name, label: user.name })) },
      { key: 'operationalStatus', label: 'Status', valueType: 'select', getValue: (candidate) => candidate.operationalStatus, options: (Object.keys(OPERATIONAL_STATUS_LABELS) as Array<keyof typeof OPERATIONAL_STATUS_LABELS>).map((status) => ({ value: status, label: OPERATIONAL_STATUS_LABELS[status] })) },
      { key: 'secondary', label: 'Descrição', valueType: 'text', getValue: (candidate) => candidate.secondary },
    ],
    [candidates, eligibleUsers]
  );

  const filteredCandidates = useMemo(
    () =>
      applyDynamicFilters(
        candidates.filter((candidate) => {
          if (flowFilter !== 'all' && candidate.workspace !== flowFilter) return false;
          if (projectFilter !== 'all' && candidate.projectId !== projectFilter) return false;
          if (statusFilter !== 'all' && candidate.operationalStatus !== statusFilter) return false;
          return true;
        }),
        dynamicConditions,
        dynamicFields
      ),
    [
      candidates,
      flowFilter,
      projectFilter,
      statusFilter,
      dynamicConditions,
      dynamicFields,
    ]
  );

  const entriesForAssignee = useMemo(
    () =>
      operationalPriorityEntries
        .filter(
          (entry) =>
            entry.assigneeId === selectedAssigneeId &&
            entry.itemType === (priorityScope === 'projects' ? 'project' : 'task')
        )
        .sort((a, b) => a.order - b.order),
    [operationalPriorityEntries, priorityScope, selectedAssigneeId]
  );

  const candidateMap = useMemo(
    () => new Map(filteredCandidates.map((candidate) => [candidate.id, candidate])),
    [filteredCandidates]
  );

  const prioritizedEntries = useMemo(
    () =>
      entriesForAssignee.filter((entry) =>
        candidateMap.has(buildCandidateId(entry.itemType, entry.itemId))
      ),
    [candidateMap, entriesForAssignee]
  );

  const prioritizedCandidates = useMemo(
    () =>
      prioritizedEntries
        .map((entry) => candidateMap.get(buildCandidateId(entry.itemType, entry.itemId)))
        .filter(Boolean) as PriorityCandidate[],
    [candidateMap, prioritizedEntries]
  );

  const prioritizedCandidateIds = new Set(prioritizedCandidates.map((candidate) => candidate.id));
  const backlogCandidates = filteredCandidates.filter((candidate) => !prioritizedCandidateIds.has(candidate.id));
  const activePriorityCycle = useMemo(
    () =>
      priorityCycles
        .slice()
        .sort((a, b) => Number(b.active) - Number(a.active) || b.createdAt.localeCompare(a.createdAt))
        .find((cycle) => cycle.active),
    [priorityCycles]
  );
  const editingCycle = useMemo(
    () => priorityCycles.find((cycle) => cycle.id === cycleDraft.editingId) || null,
    [priorityCycles, cycleDraft.editingId]
  );
  const isEditingCycleStructureLocked = useMemo(
    () => (editingCycle ? isPriorityCycleStructureLocked(editingCycle) : false),
    [editingCycle]
  );
  const activeCycleTaskIds = new Set(activePriorityCycle?.taskIds || []);
  const activeCycleProjectIds = new Set(activePriorityCycle?.projectIds || []);
  const focusedCandidateIds = new Set(
    filteredCandidates
      .filter((candidate) =>
        candidate.itemType === 'task'
          ? activeCycleTaskIds.has(candidate.entityId)
          : activeCycleProjectIds.has(candidate.entityId)
      )
      .map((candidate) => candidate.id)
  );
  const selectedUser = users.find((user) => user.id === selectedAssigneeId);
  const cycleScope = useMemo(() => {
    const relatedProjectIds = Array.from(
      new Set(
        prioritizedCandidates
          .map((candidate) =>
            candidate.itemType === 'project' ? candidate.entityId : candidate.projectId
          )
          .filter(Boolean) as string[]
      )
    );
    const taskIds = prioritizedCandidates
      .filter((candidate) => candidate.itemType === 'task')
      .map((candidate) => candidate.entityId);

    return {
      teamIds: selectedUser
        ? getUserTeams(selectedUser)
            .map((teamName) => teams.find((team) => team.name === teamName)?.id)
            .filter(Boolean) as string[]
        : [],
      projectIds: relatedProjectIds,
      taskIds,
      userIds: selectedAssigneeId ? [selectedAssigneeId] : [],
    };
  }, [prioritizedCandidates, selectedAssigneeId, selectedUser, teams]);
  const effectiveCycleScope =
    editingCycle && isEditingCycleStructureLocked
      ? {
          teamIds: editingCycle.teamIds,
          projectIds: editingCycle.projectIds,
          taskIds: editingCycle.taskIds,
          userIds: editingCycle.userIds,
        }
      : cycleScope;
  const resolvedCycleDurationDays = useMemo(() => {
    const nextDurationValue = getDraftDurationValue(cycleDraft.type, cycleDraft.durationDays);
    return cycleDraft.type === 'custom' ? null : Number(nextDurationValue);
  }, [cycleDraft.durationDays, cycleDraft.type]);
  const resolvedCycleEndDate = useMemo(() => {
    if (isPriorityCycleAutoScheduled(cycleDraft.type)) {
      if (!cycleDraft.startDate || !resolvedCycleDurationDays) return '';
      return calculatePriorityCycleEndDate(cycleDraft.startDate, resolvedCycleDurationDays);
    }
    return cycleDraft.endDate;
  }, [cycleDraft.endDate, cycleDraft.startDate, cycleDraft.type, resolvedCycleDurationDays]);
  const isCycleDraftValid =
    cycleDraft.name.trim().length > 0 &&
    cycleDraft.startDate &&
    resolvedCycleEndDate &&
    resolvedCycleEndDate >= cycleDraft.startDate &&
    (cycleDraft.type === 'custom' || Boolean(resolvedCycleDurationDays)) &&
    (effectiveCycleScope.projectIds.length > 0 || effectiveCycleScope.taskIds.length > 0);

  const handleMove = (
    candidateId: string,
    sourceList: 'prioritized' | 'backlog',
    targetList: 'prioritized' | 'backlog',
    targetCandidateId?: string,
    placement: KanbanDropPlacement = 'after'
  ) => {
    if (!canManageQueue || !selectedAssigneeId) return;

    const candidate = candidateMap.get(candidateId) || candidates.find((item) => item.id === candidateId);
    if (!candidate) return;

    const existingEntry = entriesForAssignee.find(
      (entry) => buildCandidateId(entry.itemType, entry.itemId) === candidateId
    );

    if (targetList === 'backlog') {
      if (existingEntry) {
        deleteOperationalPriorityEntry(existingEntry.id);
      }
      return;
    }

    const currentEntryIds = entriesForAssignee.map((entry) => entry.id);
    const targetEntryId = targetCandidateId
      ? entriesForAssignee.find(
          (entry) => buildCandidateId(entry.itemType, entry.itemId) === targetCandidateId
        )?.id
      : undefined;

    if (existingEntry) {
      const reorderedEntryIds = targetEntryId
        ? moveItemWithinList(currentEntryIds, existingEntry.id, targetEntryId, placement)
        : [...currentEntryIds.filter((id) => id !== existingEntry.id), existingEntry.id];

      reorderOperationalPriorityEntries(selectedAssigneeId, reorderedEntryIds, {
        itemType: priorityScope === 'projects' ? 'project' : 'task',
      });
      return;
    }

    const insertedEntryId = addOperationalPriorityEntry({
        assigneeId: selectedAssigneeId,
        itemType: candidate.itemType,
        itemId: candidate.entityId,
        order: currentEntryIds.length,
        isWeeklyFocus: false,
      });

    const reorderedEntryIds = targetEntryId
      ? moveItemBetweenLists([], currentEntryIds, insertedEntryId, targetEntryId, placement)
          .destinationIds
      : [...currentEntryIds, insertedEntryId];

    reorderOperationalPriorityEntries(selectedAssigneeId, reorderedEntryIds, {
      itemType: priorityScope === 'projects' ? 'project' : 'task',
    });
  };

  const handleRemove = (candidateId: string) => {
    if (!canManageQueue) return;
    const entry = entriesForAssignee.find(
      (item) => buildCandidateId(item.itemType, item.itemId) === candidateId
    );
    if (!entry) return;
    deleteOperationalPriorityEntry(entry.id);
  };

  const handleApplySavedView = (view: SavedView) => {
    setDynamicConditions(view.filtersJson || []);
    if (view.viewMode === 'projects' || view.viewMode === 'tasks') {
      setPriorityScope(view.viewMode as PriorityScope);
    }
    setActiveSavedViewId(view.id);
  };

  const handleSaveDynamicView = (viewId?: string) => {
    const current = viewId ? views.find((item) => item.id === viewId) : undefined;
    const name = window.prompt('Nome da visualização', current?.name || '');
    if (!name?.trim()) return;
    const saved = saveView({
      id: viewId,
      name: name.trim(),
      filtersJson: dynamicConditions,
      viewMode: priorityScope,
    });
    if (saved) setActiveSavedViewId(saved.id);
  };

  const resetCycleDraft = () => {
    setCycleDraft(createInitialCycleDraft());
  };

  const handleCycleNameChange = (value: string) => {
    setCycleDraft((current) => ({
      ...current,
      name: value,
      nameAutoGenerated: false,
    }));
  };

  const handleCycleTypeChange = (type: PriorityCycleType) => {
    setCycleDraft((current) => {
      const durationDays = getDraftDurationValue(type, current.durationDays);
      const shouldRefreshName = current.nameAutoGenerated || !current.name.trim();
      const nextName =
        type === 'custom'
          ? shouldRefreshName
            ? ''
            : current.name
          : shouldRefreshName
            ? getCycleSuggestedName(type, current.startDate, current.editingId)
            : current.name;

      return {
        ...current,
        type,
        durationDays,
        endDate:
          type === 'custom'
            ? current.endDate
            : calculatePriorityCycleEndDate(current.startDate, Number(durationDays)),
        name: nextName,
        nameAutoGenerated: type === 'custom' ? false : shouldRefreshName,
      };
    });
  };

  const handleCycleStartDateChange = (startDate: string) => {
    setCycleDraft((current) => {
      const shouldRefreshName = current.nameAutoGenerated || !current.name.trim();
      return {
        ...current,
        startDate,
        endDate:
          current.type === 'custom'
            ? current.endDate
            : calculatePriorityCycleEndDate(
                startDate,
                Number(getDraftDurationValue(current.type, current.durationDays))
              ),
        name:
          current.type === 'custom' || !shouldRefreshName
            ? current.name
            : getCycleSuggestedName(current.type, startDate, current.editingId),
        nameAutoGenerated: current.type === 'custom' ? false : shouldRefreshName,
      };
    });
  };

  const handleCycleDurationChange = (durationDays: string) => {
    setCycleDraft((current) => {
      const nextDuration = getDraftDurationValue(current.type, durationDays);
      return {
        ...current,
        durationDays: nextDuration,
        endDate:
          current.type === 'custom'
            ? current.endDate
            : calculatePriorityCycleEndDate(current.startDate, Number(nextDuration)),
      };
    });
  };

  const handleEditCycle = (cycle: PriorityCycle) => {
    const suggestedName = getCycleSuggestedName(cycle.type, cycle.startDate, cycle.id);
    const durationDays = getPriorityCycleDurationDays(cycle);
    setCycleDraft({
      editingId: cycle.id,
      name: cycle.name,
      description: cycle.description || '',
      type: cycle.type,
      startDate: cycle.startDate,
      endDate: cycle.endDate,
      durationDays: durationDays ? String(durationDays) : '',
      active: cycle.active,
      nameAutoGenerated: cycle.type !== 'custom' && cycle.name.trim() === suggestedName,
    });
  };

  const handleSaveCycle = () => {
    if (!canManageFocus || !isCycleDraftValid || !currentUser) return;

    const durationDays =
      cycleDraft.type === 'custom'
        ? getPriorityCycleDurationDays({
            type: cycleDraft.type,
            startDate: cycleDraft.startDate,
            endDate: resolvedCycleEndDate,
            durationDays: undefined,
          }) || undefined
        : resolvedCycleDurationDays || undefined;
    const scopeSource =
      editingCycle && isEditingCycleStructureLocked
        ? {
            teamIds: editingCycle.teamIds,
            projectIds: editingCycle.projectIds,
            taskIds: editingCycle.taskIds,
            userIds: editingCycle.userIds,
          }
        : effectiveCycleScope;
    const payload = {
      name: cycleDraft.name.trim(),
      description: cycleDraft.description.trim(),
      type: cycleDraft.type,
      startDate: cycleDraft.startDate,
      endDate: resolvedCycleEndDate,
      durationDays,
      createdBy: currentUser.id,
      teamIds: scopeSource.teamIds,
      projectIds: scopeSource.projectIds,
      taskIds: scopeSource.taskIds,
      userIds: scopeSource.userIds,
      active: cycleDraft.active,
    };

    if (cycleDraft.editingId) {
      updatePriorityCycle(cycleDraft.editingId, payload);
    } else {
      addPriorityCycle(payload);
    }

    resetCycleDraft();
  };

  const handleToggleFocus = (candidate: PriorityCandidate) => {
    if (!showFocusManagement || !currentUser) return;

    const activeCycle = activePriorityCycle;
    const nextProjectIds = new Set(activeCycle?.projectIds || []);
    const nextTaskIds = new Set(activeCycle?.taskIds || []);

    if (candidate.itemType === 'project') {
      if (nextProjectIds.has(candidate.entityId)) nextProjectIds.delete(candidate.entityId);
      else nextProjectIds.add(candidate.entityId);
    } else {
      if (nextTaskIds.has(candidate.entityId)) nextTaskIds.delete(candidate.entityId);
      else nextTaskIds.add(candidate.entityId);
    }

    if (activeCycle) {
      updatePriorityCycle(activeCycle.id, {
        projectIds: Array.from(nextProjectIds),
        taskIds: Array.from(nextTaskIds),
      });
      return;
    }

    const fallbackDraft = createInitialCycleDraft();
    const fallbackType = cycleDraft.type || fallbackDraft.type;
    const fallbackDuration = getDraftDurationValue(fallbackType, cycleDraft.durationDays || fallbackDraft.durationDays);
    const fallbackStartDate = cycleDraft.startDate || fallbackDraft.startDate;
    const fallbackEndDate = isPriorityCycleAutoScheduled(fallbackType)
      ? calculatePriorityCycleEndDate(fallbackStartDate, Number(fallbackDuration))
      : cycleDraft.endDate || fallbackDraft.endDate;
    addPriorityCycle({
      name:
        cycleDraft.name.trim() ||
        getCycleSuggestedName(fallbackType, fallbackStartDate) ||
        `Foco ${fallbackStartDate}`,
      description:
        cycleDraft.description.trim() ||
        'Ciclo criado automaticamente ao marcar foco na priorização oficial.',
      type: fallbackType,
      startDate: fallbackStartDate,
      endDate: fallbackEndDate,
      durationDays: fallbackType === 'custom' ? undefined : Number(fallbackDuration),
      createdBy: currentUser.id,
      teamIds: selectedUser
        ? getUserTeams(selectedUser)
            .map((teamName) => teams.find((team) => team.name === teamName)?.id)
            .filter(Boolean) as string[]
        : [],
      projectIds: Array.from(nextProjectIds),
      taskIds: Array.from(nextTaskIds),
      userIds: selectedAssigneeId ? [selectedAssigneeId] : [],
      active: true,
    });
  };

  const flowOptions = Array.from(new Set(candidates.map((candidate) => candidate.workspace))).filter(Boolean);
  const projectOptions = projects.filter((project) =>
    candidates.some((candidate) => candidate.projectId === project.id)
  );
  const statusOptions = (
    Object.keys(OPERATIONAL_STATUS_LABELS) as Array<keyof typeof OPERATIONAL_STATUS_LABELS>
  ).filter((status) =>
    candidates.some((candidate) => candidate.operationalStatus === status)
  );
  const assigneeFilterOptions = [
    { value: selectedAssigneeId, label: eligibleUsers.find((user) => user.id === selectedAssigneeId)?.name || 'Selecionado' },
    ...eligibleUsers
      .filter((user) => user.id !== selectedAssigneeId)
      .map((user) => ({ value: user.id, label: user.name })),
  ];
  const flowFilterOptions = [
    { value: 'all', label: 'Todos os fluxos' },
    ...flowOptions.map((workspace) => ({ value: workspace, label: workspace })),
  ];
  const projectFilterOptions = [
    { value: 'all', label: 'Todos os projetos' },
    ...projectOptions.map((project) => ({ value: project.id, label: project.name })),
  ];
  const statusFilterOptions = [
    { value: 'all', label: 'Todos os status' },
    ...statusOptions.map((status) => ({ value: status, label: OPERATIONAL_STATUS_LABELS[status] })),
  ];
  const activeFilterChips = [
    { key: `scope-${priorityScope}`, label: priorityScope === 'projects' ? 'Priorizando projetos' : 'Priorizando tarefas' },
    ...(flowFilter !== 'all'
      ? [{ key: `flow-${flowFilter}`, label: `Fluxo: ${flowFilter}` }]
      : []),
    ...(projectFilter !== 'all'
      ? [{ key: `project-${projectFilter}`, label: `Projeto: ${projectOptions.find((project) => project.id === projectFilter)?.name || projectFilter}` }]
      : []),
    ...(statusFilter !== 'all'
      ? [{ key: `status-${statusFilter}`, label: `Status: ${OPERATIONAL_STATUS_LABELS[statusFilter as keyof typeof OPERATIONAL_STATUS_LABELS]}` }]
      : []),
    ...(dynamicConditions.length > 0
      ? [{ key: 'dynamic-rules', label: `${dynamicConditions.length} regra${dynamicConditions.length > 1 ? 's' : ''} dinâmica${dynamicConditions.length > 1 ? 's' : ''}` }]
      : []),
  ];

  if (!canAccessPage) {
    return (
      <div className="h-full flex items-center justify-center bg-gray-50">
          <div className="rounded-2xl border border-red-200 bg-white px-8 py-10 text-center shadow-sm">
            <h1 className="text-2xl font-bold text-gray-900">Acesso restrito</h1>
            <p className="mt-2 text-gray-600">
            Seu perfil atual não possui permissão para editar priorização ou foco da semana.
            </p>
          </div>
        </div>
    );
  }

  return (
    <DndProvider backend={HTML5Backend}>
      <div className={embedded ? 'space-y-6' : 'min-h-screen bg-gray-50'}>
        {!embedded && (
          <div className="border-b border-gray-200 bg-white px-8 py-6">
          <div className="flex items-center gap-3">
            <div className="rounded-xl bg-indigo-100 p-3">
              <ListOrdered className="h-6 w-6 text-indigo-600" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-gray-900">Prioridade Operacional</h1>
              <p className="text-gray-600">
                Monte a fila oficial de execução por colaborador, sem alterar a governança macro.
              </p>
            </div>
          </div>
          </div>
        )}

        <div className={embedded ? 'space-y-6' : 'space-y-6 px-8 py-6'}>
          {showFocusManagement ? (
          <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
            <div className="flex flex-wrap items-start justify-between gap-4">
              <div>
                <h2 className="text-lg font-semibold text-slate-900">Ciclos de prioridade</h2>
                <p className="mt-1 text-sm text-slate-600">
                  O foco operacional agora vem exclusivamente de ciclos definidos pela governança.
                </p>
              </div>
              {activePriorityCycle ? (
                <span className="inline-flex rounded-full bg-sky-100 px-3 py-1 text-xs font-semibold text-sky-700">
                  Ciclo ativo: {activePriorityCycle.name}
                </span>
              ) : (
                <span className="inline-flex rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-600">
                  Nenhum ciclo ativo
                </span>
              )}
            </div>

            <div className="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1.2fr)_minmax(0,1fr)]">
              <div className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4">
                <div className="grid grid-cols-1 gap-4 md:grid-cols-2">
                  <FilterField label="Nome do ciclo">
                    <input
                      type="text"
                      value={cycleDraft.name}
                      onChange={(event) => handleCycleNameChange(event.target.value)}
                      placeholder={
                        cycleDraft.type === 'sprint'
                          ? 'Ex.: Sprint 4'
                          : cycleDraft.type === 'week'
                            ? 'Ex.: Semana de 07/04'
                            : 'Ex.: Janela de estabilização'
                      }
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    <p className="mt-1 text-xs text-slate-500">
                      {cycleDraft.type === 'custom'
                        ? 'Personalizado mantém nome totalmente livre.'
                        : 'Nome sugerido automaticamente pelo tipo, com liberdade para ajuste manual.'}
                    </p>
                  </FilterField>
                  <FilterField label="Tipo">
                    <select
                      value={cycleDraft.type}
                      onChange={(event) => handleCycleTypeChange(event.target.value as PriorityCycleType)}
                      disabled={isEditingCycleStructureLocked}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    >
                      <option value="week">Semanal</option>
                      <option value="custom">Personalizado</option>
                      <option value="sprint">Sprint</option>
                    </select>
                    <div className="mt-2 flex flex-wrap items-center gap-2">
                      <span
                        className={`inline-flex rounded-full px-2.5 py-1 text-[11px] font-semibold ${getPriorityCycleTypeBadgeClasses(
                          cycleDraft.type
                        )}`}
                      >
                        {getPriorityCycleTypeLabel(cycleDraft.type)}
                      </span>
                      <span className="text-xs text-slate-500">
                        {cycleDraft.type === 'week'
                          ? '7 dias, foco recorrente e data final automatica.'
                          : cycleDraft.type === 'sprint'
                            ? 'Janela fechada com foco em execucao e travamento estrutural apos inicio.'
                            : 'Sem automacoes, nome e periodo livres.'}
                      </span>
                    </div>
                  </FilterField>
                  <FilterField label="Início">
                    <input
                      type="date"
                      value={cycleDraft.startDate}
                      onChange={(event) => handleCycleStartDateChange(event.target.value)}
                      disabled={isEditingCycleStructureLocked}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                  </FilterField>
                  {cycleDraft.type === 'sprint' ? (
                    <FilterField label="Duração do sprint (dias)">
                      <input
                        type="number"
                        min={1}
                        step={1}
                        value={cycleDraft.durationDays}
                        onChange={(event) => handleCycleDurationChange(event.target.value)}
                        disabled={isEditingCycleStructureLocked}
                        className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                      <p className="mt-1 text-xs text-slate-500">
                        Use 7, 14 ou outro período que represente sua cadência real.
                      </p>
                    </FilterField>
                  ) : null}
                  <FilterField label="Fim">
                    <input
                      type="date"
                      value={resolvedCycleEndDate}
                      onChange={(event) =>
                        setCycleDraft((current) => ({ ...current, endDate: event.target.value }))
                      }
                      readOnly={cycleDraft.type !== 'custom'}
                      disabled={isEditingCycleStructureLocked}
                      className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                    />
                    <p className="mt-1 text-xs text-slate-500">
                      {cycleDraft.type === 'week'
                        ? 'Fechamento automático em 7 dias a partir do início.'
                        : cycleDraft.type === 'sprint'
                          ? 'Calculado automaticamente com base na duração do sprint.'
                          : 'Período livre para ciclos sem automação.'}
                    </p>
                  </FilterField>
                  <div className="md:col-span-2">
                    <FilterField label="Descrição">
                      <textarea
                        value={cycleDraft.description}
                        onChange={(event) => setCycleDraft((current) => ({ ...current, description: event.target.value }))}
                        placeholder="Explique o objetivo e o contexto do ciclo."
                        rows={3}
                        className="w-full rounded-lg border border-gray-300 px-3 py-2 focus:outline-none focus:ring-2 focus:ring-blue-500"
                      />
                    </FilterField>
                  </div>
                </div>

                {isEditingCycleStructureLocked ? (
                  <div className="mt-4 rounded-xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-900">
                    Sprint já iniciada: tipo, período e itens vinculados ficam preservados para evitar mudança estrutural no meio da execução.
                  </div>
                ) : null}

                <div className="mt-4 flex flex-wrap items-center gap-4 text-sm text-slate-600">
                  <label className="inline-flex items-center gap-2">
                    <input
                      type="checkbox"
                      checked={cycleDraft.active}
                      onChange={(event) => setCycleDraft((current) => ({ ...current, active: event.target.checked }))}
                      className="h-4 w-4 rounded border-gray-300 text-blue-600 focus:ring-blue-500"
                    />
                    Ativar este ciclo ao salvar
                  </label>
                  <span>Projetos vinculados: <strong className="text-slate-900">{effectiveCycleScope.projectIds.length}</strong></span>
                  <span>Tarefas vinculadas: <strong className="text-slate-900">{effectiveCycleScope.taskIds.length}</strong></span>
                  <span>Usuarios alvo: <strong className="text-slate-900">{effectiveCycleScope.userIds.length}</strong></span>
                  {resolvedCycleDurationDays ? (
                    <span>Duração aplicada: <strong className="text-slate-900">{resolvedCycleDurationDays} dias</strong></span>
                  ) : null}
                </div>

                <p className="mt-3 text-xs text-slate-500">
                  {isEditingCycleStructureLocked
                    ? 'Este sprint mantém a estrutura original para preservar a execução iniciada.'
                    : 'Este ciclo usa a fila priorizada atual como origem. Monte a fila do colaborador ou do projeto e salve o ciclo para propagar o foco na aplicação inteira.'}
                </p>

                <div className="mt-4 flex flex-wrap gap-3">
                  <button
                    type="button"
                    onClick={handleSaveCycle}
                    disabled={!isCycleDraftValid}
                    className="inline-flex items-center gap-2 rounded-lg bg-slate-900 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    <Save className="h-4 w-4" />
                    {cycleDraft.editingId ? 'Atualizar ciclo' : 'Criar ciclo'}
                  </button>
                  <button
                    type="button"
                    onClick={resetCycleDraft}
                    className="inline-flex items-center gap-2 rounded-lg border border-slate-300 px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
                  >
                    <X className="h-4 w-4" />
                    Limpar
                  </button>
                </div>
              </div>

              <div className="rounded-2xl border border-slate-200 bg-white p-4">
                <h3 className="text-sm font-semibold uppercase tracking-[0.14em] text-slate-500">
                  Ciclos cadastrados
                </h3>
                <div className="mt-3 space-y-3">
                  {priorityCycles.length > 0 ? (
                    priorityCycles
                      .slice()
                      .sort((a, b) => Number(b.active) - Number(a.active) || b.createdAt.localeCompare(a.createdAt))
                      .map((cycle) => (
                        <div key={cycle.id} className={`rounded-xl border px-4 py-3 ${cycle.active ? 'border-sky-200 bg-sky-50/70' : 'border-slate-200 bg-slate-50/60'}`}>
                          <div className="flex flex-wrap items-start justify-between gap-3">
                            <div>
                              <div className="flex flex-wrap items-center gap-2">
                                <p className="text-sm font-semibold text-slate-900">{cycle.name}</p>
                                {cycle.active ? (
                                  <span className="rounded-full bg-sky-100 px-2 py-0.5 text-[11px] font-semibold text-sky-700">Ativo</span>
                                ) : null}
                                <span
                                  className={`rounded-full px-2 py-0.5 text-[11px] font-medium ${getPriorityCycleTypeBadgeClasses(
                                    cycle.type
                                  )}`}
                                >
                                  {getPriorityCycleTypeLabel(cycle.type)}
                                </span>
                                {isPriorityCycleStructureLocked(cycle) ? (
                                  <span className="rounded-full bg-amber-100 px-2 py-0.5 text-[11px] font-semibold text-amber-800">
                                    Estrutura bloqueada
                                  </span>
                                ) : null}
                              </div>
                              <p className="mt-1 text-xs text-slate-600">
                                {cycle.startDate} ate {cycle.endDate} • {getPriorityCycleBehaviorLabel(cycle)} • {cycle.projectIds.length} projetos • {cycle.taskIds.length} tarefas
                              </p>
                              {cycle.description ? (
                                <p className="mt-2 text-xs text-slate-500">{cycle.description}</p>
                              ) : null}
                            </div>
                            <div className="flex flex-wrap gap-2">
                              <button
                                type="button"
                                onClick={() => handleEditCycle(cycle)}
                                className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-white"
                              >
                                Editar
                              </button>
                              <button
                                type="button"
                                onClick={() => setPriorityCycleActive(cycle.id, !cycle.active)}
                                className="rounded-lg border border-slate-200 px-3 py-1.5 text-xs font-medium text-slate-700 hover:bg-white"
                              >
                                {cycle.active ? 'Desativar' : 'Ativar'}
                              </button>
                              <button
                                type="button"
                                onClick={() => deletePriorityCycle(cycle.id)}
                                className="rounded-lg border border-red-200 px-3 py-1.5 text-xs font-medium text-red-600 hover:bg-red-50"
                              >
                                Excluir
                              </button>
                            </div>
                          </div>
                        </div>
                      ))
                  ) : (
                    <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 px-4 py-8 text-center text-sm text-slate-500">
                      Nenhum ciclo cadastrado ainda. Monte uma fila priorizada e salve o primeiro ciclo de foco.
                    </div>
                  )}
                </div>
              </div>
            </div>
          </section>
          ) : null}

          <AppErrorBoundary
            area="operational-priority-filters"
            title="Os filtros de prioridade operacional falharam"
            message="A fila priorizada continua acessivel mesmo se este bloco apresentar erro."
          >
            <UnifiedFilterPanel
              title="Filtros da priorização"
              subtitle="Mantenha busca, filtros operacionais e visualizações salvas no mesmo bloco para montar e reaplicar recortes com mais fluidez."
              expanded={showFilters}
              onToggleExpanded={() => setShowFilters((prev) => !prev)}
              activeFiltersCount={activeFilterChips.length}
              activeFiltersSlot={
                activeFilterChips.length > 0 ? (
                  <>
                    {activeFilterChips.map((chip) => (
                      <span
                        key={chip.key}
                        className="inline-flex items-center rounded-full border border-slate-200 bg-slate-50 px-3 py-1 text-xs font-medium text-slate-700"
                      >
                        {chip.label}
                      </span>
                    ))}
                  </>
                ) : null
              }
              compactHelperText="Abra os filtros quando precisar refinar a fila oficial do colaborador."
              compactByDefault
              actionsSlot={
                <>
                  <button
                    type="button"
                    onClick={() => handleSaveDynamicView(activeSavedViewId || undefined)}
                    className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm text-slate-700 transition-colors hover:bg-slate-50"
                  >
                    <Save className="h-4 w-4" />
                    {activeSavedViewId ? 'Atualizar visualização' : 'Salvar visualização'}
                  </button>
                  <button
                    type="button"
                    onClick={() => {
                      setFlowFilter('all');
                      setProjectFilter('all');
                      setStatusFilter('all');
                      setDynamicConditions([]);
                      setActiveSavedViewId(null);
                    }}
                    className="inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-4 py-2 text-sm text-slate-700 transition-colors hover:bg-slate-50"
                  >
                    <X className="h-4 w-4" />
                    Limpar filtros
                  </button>
                </>
              }
              filtersSlot={
                <>
                  <div className="mb-4 inline-flex rounded-xl bg-gray-100 p-1">
                    {([
                      { value: 'projects', label: 'Priorizar projetos', subtitle: 'Fila macro de governança e equipe' },
                      { value: 'tasks', label: 'Priorizar tarefas', subtitle: 'Fila operacional do colaborador' },
                    ] as Array<{ value: PriorityScope; label: string; subtitle: string }>).map((scope) => (
                      <button
                        key={scope.value}
                        type="button"
                        onClick={() => {
                          setPriorityScope(scope.value);
                          setProjectFilter('all');
                          setFlowFilter('all');
                          setStatusFilter('all');
                        }}
                        className={`rounded-lg px-4 py-3 text-left transition-colors ${
                          priorityScope === scope.value
                            ? 'bg-white text-gray-900 shadow-sm'
                            : 'text-gray-600 hover:text-gray-900'
                        }`}
                      >
                        <p className="text-sm font-semibold">{scope.label}</p>
                        <p className="text-xs text-gray-500">{scope.subtitle}</p>
                      </button>
                    ))}
                  </div>

                  {selectedAssigneeId ? (
                    <div className="mb-4 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600">
                      Fluxos do colaborador selecionado:{' '}
                      <span className="font-medium text-slate-900">
                        {getUserTeams(users.find((user) => user.id === selectedAssigneeId)).join(', ') || 'Sem equipe vinculada'}
                      </span>
                    </div>
                  ) : null}

                  {showFilters ? (
                    <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">
                      <FilterField label="Colaborador">
                        <SearchableSelect
                          value={selectedAssigneeId}
                          onChange={setSelectedAssigneeId}
                          placeholder="Selecione um colaborador"
                          allLabel="Selecionado"
                          searchPlaceholder="Buscar colaborador..."
                          options={assigneeFilterOptions}
                        />
                      </FilterField>

                      <FilterField label="Fluxo / equipe">
                        <SearchableSelect
                          value={flowFilter}
                          onChange={setFlowFilter}
                          placeholder="Todos os fluxos"
                          allLabel="Todas"
                          searchPlaceholder="Buscar fluxo..."
                          options={flowFilterOptions}
                        />
                      </FilterField>

                      <FilterField label="Projeto">
                        <SearchableSelect
                          value={projectFilter}
                          onChange={setProjectFilter}
                          placeholder="Todos os projetos"
                          allLabel="Todos"
                          searchPlaceholder="Buscar projeto..."
                          options={projectFilterOptions}
                        />
                      </FilterField>

                      <FilterField label="Status">
                        <SearchableSelect
                          value={statusFilter}
                          onChange={setStatusFilter}
                          placeholder="Todos os status"
                          allLabel="Todos"
                          searchPlaceholder="Buscar status..."
                          options={statusFilterOptions}
                        />
                      </FilterField>
                    </div>
                  ) : null}
                </>
              }
              savedViewsSlot={
                <DynamicFiltersPanel
                  embedded
                  showHeader={false}
                  showActions={false}
                  fields={dynamicFields}
                  conditions={dynamicConditions}
                  onConditionsChange={setDynamicConditions}
                  savedViews={views}
                  activeViewId={activeSavedViewId}
                  pinnedViewId={pinnedView?.id || null}
                  activeViewLabel={
                    activeSavedViewId
                      ? views.find((view) => view.id === activeSavedViewId)?.name
                      : dynamicConditions.length > 0
                        ? 'Temporária'
                        : 'Sem filtros'
                  }
                  onApplyView={handleApplySavedView}
                  onSaveView={handleSaveDynamicView}
                  onDeleteView={(viewId) => {
                    if (activeSavedViewId === viewId) setActiveSavedViewId(null);
                    deleteView(viewId);
                  }}
                  onPinView={pinView}
                  onClearPinned={clearPinnedView}
                  onClearFilters={() => {
                    setDynamicConditions([]);
                    setActiveSavedViewId(null);
                  }}
                />
              }
            />
          </AppErrorBoundary>

          <div className="grid grid-cols-1 gap-6 xl:grid-cols-2">
            <PriorityList
              title={priorityScope === 'projects' ? 'Projetos priorizados' : 'Tarefas priorizadas'}
              subtitle={
                priorityScope === 'projects'
                  ? 'Fila macro oficial para este responsável.'
                  : 'Fila operacional oficial de execução do colaborador.'
              }
              candidates={prioritizedCandidates}
              listType="prioritized"
              focusedEntryIds={focusedCandidateIds}
              canManageQueue={canManageQueue}
              canManageFocus={showFocusManagement}
              onMove={handleMove}
              onRemove={handleRemove}
              onToggleFocus={handleToggleFocus}
            />

            <PriorityList
              title={priorityScope === 'projects' ? 'Projetos sem priorização' : 'Tarefas sem priorização'}
              subtitle={
                priorityScope === 'projects'
                  ? 'Backlog de projetos disponível para compor a fila macro.'
                  : 'Backlog operacional disponível para compor a fila do colaborador.'
              }
              candidates={backlogCandidates}
              listType="backlog"
              focusedEntryIds={focusedCandidateIds}
              canManageQueue={canManageQueue}
              canManageFocus={showFocusManagement}
              onMove={handleMove}
              onRemove={handleRemove}
              onToggleFocus={handleToggleFocus}
            />
          </div>

          <section className="rounded-2xl border border-blue-200 bg-blue-50 px-5 py-4 text-sm text-blue-900">
            {showFocusManagement
              ? 'A edição do foco da semana fica restrita a esta tela completa de priorização/governança. Nas telas operacionais, o sistema apenas propaga e exibe o destaque.'
              : 'Nesta visão operacional embutida, o foco da semana é apenas visual. A edição permanece disponível somente na priorização completa.'}
          </section>
        </div>
      </div>
    </DndProvider>
  );
}

export function OperationalPriority() {
  return <OperationalPriorityContent />;
}

function FilterField({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div>
      <label className="mb-1.5 block text-sm font-medium text-gray-700">{label}</label>
      {children}
    </div>
  );
}
