import { EAP, Project, WBSTask } from '../types';

/**
 * Template EAP para teste do Gantt
 */
export const testEAPTemplate: EAP = {
  id: 'test-eap-gantt',
  name: 'Test EAP - Gantt',
  description: 'EAP de teste para validar visualização Gantt',
  isActive: true,
  phases: [
    {
      id: 'test-phase-1',
      name: 'Análise',
      description: 'Fase de análise de requisitos',
      order: 1,
      startDate: '2024-01-01',
      endDate: '2024-01-31',
      milestones: [],
    },
    {
      id: 'test-phase-2',
      name: 'Desenvolvimento',
      description: 'Fase de desenvolvimento',
      order: 2,
      startDate: '2024-02-01',
      endDate: '2024-04-30',
      milestones: [],
    },
    {
      id: 'test-phase-3',
      name: 'Testes',
      description: 'Fase de testes e validação',
      order: 3,
      startDate: '2024-05-01',
      endDate: '2024-05-31',
      milestones: [],
    },
    {
      id: 'test-phase-4',
      name: 'Implantação',
      description: 'Fase de implantação em produção',
      order: 4,
      startDate: '2024-06-01',
      endDate: '2024-06-15',
      milestones: [],
    },
  ],
};

/**
 * Projeto de teste com EAP e fases datadas
 */
export const testProjectData: Project = {
  id: 'test-project-gantt',
  name: '🧪 Projeto Teste - Gantt',
  description: 'Projeto de teste para validar visualização Gantt e funcionalidades de EAP',
  responsible: 'Teste',
  client: 'Interno',
  group: 'Testes',
  status: 'backlog',
  situation: 'ativo',
  purpose: 'inovacao',
  eapId: 'test-eap-gantt',
  progress: 0,
  tasksCompleted: 0,
  tasksTotal: 0,
  hoursRemaining: 100,
  deadline: '2024-06-15',
  logoColor: '#3b82f6',
  coverImage: '',
  isPaused: false,
  quadro: 'Backlog',
  tags: ['Teste', 'Gantt'],
  phases: [
    {
      id: 'test-phase-1',
      name: 'Análise',
      description: 'Fase de análise de requisitos',
      order: 1,
      startDate: '2024-01-01',
      endDate: '2024-01-31',
      milestones: [],
    },
    {
      id: 'test-phase-2',
      name: 'Desenvolvimento',
      description: 'Fase de desenvolvimento',
      order: 2,
      startDate: '2024-02-01',
      endDate: '2024-04-30',
      milestones: [],
    },
    {
      id: 'test-phase-3',
      name: 'Testes',
      description: 'Fase de testes e validação',
      order: 3,
      startDate: '2024-05-01',
      endDate: '2024-05-31',
      milestones: [],
    },
    {
      id: 'test-phase-4',
      name: 'Implantação',
      description: 'Fase de implantação em produção',
      order: 4,
      startDate: '2024-06-01',
      endDate: '2024-06-15',
      milestones: [],
    },
  ],
};

/**
 * Tasks de teste distribuídas entre as fases
 */
export const testTasksData: WBSTask[] = [
  // Fase 1: Análise (4 tasks)
  {
    id: 'test-task-1',
    title: 'Documento de requisitos',
    description: 'Preparar documento com requisitos funcionais',
    status: 'done',
    assignee: 'João Silva',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-1',
    dueDate: '2024-01-15',
    order: 1,
    subtasks: [],
  },
  {
    id: 'test-task-2',
    title: 'Levantamento de riscos',
    description: 'Identificar riscos do projeto',
    status: 'done',
    assignee: 'Maria Santos',
    priority: 'medium',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-1',
    dueDate: '2024-01-20',
    order: 2,
    subtasks: [],
  },
  {
    id: 'test-task-3',
    title: 'Definição de arquitetura',
    description: 'Definir arquitetura técnica da solução',
    status: 'doing',
    assignee: 'Carlos Costa',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-1',
    dueDate: '2024-01-28',
    order: 3,
    subtasks: [],
  },
  {
    id: 'test-task-4',
    title: 'Aprovação do escopo',
    description: 'Obter aprovação do escopo com stakeholders',
    status: 'todo',
    assignee: 'Ana Paula',
    priority: 'medium',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-1',
    dueDate: '2024-01-31',
    order: 4,
    subtasks: [],
  },

  // Fase 2: Desenvolvimento (5 tasks)
  {
    id: 'test-task-5',
    title: 'Setup do ambiente de desenvolvimento',
    description: 'Configurar ambiente dev',
    status: 'done',
    assignee: 'Pedro Oliveira',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-2',
    dueDate: '2024-02-10',
    order: 1,
    subtasks: [],
  },
  {
    id: 'test-task-6',
    title: 'Desenvolvimento do backend',
    description: 'Implementar APIs backend',
    status: 'doing',
    assignee: 'João Silva',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-2',
    dueDate: '2024-03-31',
    order: 2,
    subtasks: [],
  },
  {
    id: 'test-task-7',
    title: 'Desenvolvimento do frontend',
    description: 'Implementar interface web',
    status: 'doing',
    assignee: 'Maria Santos',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-2',
    dueDate: '2024-03-31',
    order: 3,
    subtasks: [],
  },
  {
    id: 'test-task-8',
    title: 'Integração de sistemas',
    description: 'Integrar backend com frontend',
    status: 'doing',
    assignee: 'Carlos Costa',
    priority: 'medium',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-2',
    dueDate: '2024-04-15',
    order: 4,
    subtasks: [],
  },
  {
    id: 'test-task-9',
    title: 'Documentação técnica',
    description: 'Documentar código e arquitetura',
    status: 'todo',
    assignee: 'Ana Paula',
    priority: 'low',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-2',
    dueDate: '2024-04-30',
    order: 5,
    subtasks: [],
  },

  // Fase 3: Testes (3 tasks)
  {
    id: 'test-task-10',
    title: 'Testes unitários',
    description: 'Executar testes unitários',
    status: 'done',
    assignee: 'Pedro Oliveira',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-3',
    dueDate: '2024-05-10',
    order: 1,
    subtasks: [],
  },
  {
    id: 'test-task-11',
    title: 'Testes de integração',
    description: 'Testar integração dos módulos',
    status: 'done',
    assignee: 'João Silva',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-3',
    dueDate: '2024-05-20',
    order: 2,
    subtasks: [],
  },
  {
    id: 'test-task-12',
    title: 'Testes de performance',
    description: 'Validar performance do sistema',
    status: 'done',
    assignee: 'Carlos Costa',
    priority: 'medium',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-3',
    dueDate: '2024-05-31',
    order: 3,
    subtasks: [],
  },

  // Fase 4: Implantação (2 tasks)
  {
    id: 'test-task-13',
    title: 'Preparação de produção',
    description: 'Preparar ambiente de produção',
    status: 'todo',
    assignee: 'Ana Paula',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-4',
    dueDate: '2024-06-10',
    order: 1,
    subtasks: [],
  },
  {
    id: 'test-task-14',
    title: 'Deploy em produção',
    description: 'Realizar deploy da solução',
    status: 'todo',
    assignee: 'Pedro Oliveira',
    priority: 'high',
    projectId: 'test-project-gantt',
    phaseId: 'test-phase-4',
    dueDate: '2024-06-15',
    order: 2,
    subtasks: [],
  },
];
